In [2]:
# комменарий
%matplotlib inline 
#команда об интерактивном использовании matplotlib
import matplotlib.pyplot as plt #импорт функций подмодуля pyplot об интерактивном 
#использовании matplotlib


from numpy import * #при этом отсутсвует необходимость использования numpy.array
#import nympy as np - позволяет сократить имя объекта используя np.array

### Задание 1
Создайте матрицу таблицы умножения с использованием списков

In [3]:
M = array([[j*i for j in range(1,11)] for i in range(2, 11)])

M

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### Задание 2
Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии. 

In [4]:
def make_diagonal_matrix(n, el1, d):
    return diag([el1 + d*i for i in range(n)])

make_diagonal_matrix(5, 2, 1.5)

array([[2. , 0. , 0. , 0. , 0. ],
       [0. , 3.5, 0. , 0. , 0. ],
       [0. , 0. , 5. , 0. , 0. ],
       [0. , 0. , 0. , 6.5, 0. ],
       [0. , 0. , 0. , 0. , 8. ]])

### Задание 3
Из данных по температуре в Стокгольме выбрать данные относящиеся к октябрю 1970 года и записать их в бинарный и текстовый файлы oct70.bin и oct70.txt. Затем прочитайте их импортировав в тетрадь ноутбука и сравните.

In [5]:
data = genfromtxt("data/stockholm_td_adj.dat")
arr_data = array([data[i, 5] for i in range(data.shape[0]) if (data[i, 0] == 1970) * (data[i, 1] == 10)])
savetxt("oct70.bin", arr_data)
savetxt("oct70.txt", arr_data)
txt_final = loadtxt("oct70.txt")
bin_final = loadtxt('oct70.bin')

for i in range(31):
    print(f"Температура в txt файле = {txt_final[i]}, в bin файле = {bin_final[i]}.")

Температура в txt файле = 10.4, в bin файле = 10.4.
Температура в txt файле = 9.0, в bin файле = 9.0.
Температура в txt файле = 7.8, в bin файле = 7.8.
Температура в txt файле = 6.6, в bin файле = 6.6.
Температура в txt файле = 7.9, в bin файле = 7.9.
Температура в txt файле = 10.7, в bin файле = 10.7.
Температура в txt файле = 12.2, в bin файле = 12.2.
Температура в txt файле = 12.2, в bin файле = 12.2.
Температура в txt файле = 10.2, в bin файле = 10.2.
Температура в txt файле = 10.9, в bin файле = 10.9.
Температура в txt файле = 9.7, в bin файле = 9.7.
Температура в txt файле = 9.0, в bin файле = 9.0.
Температура в txt файле = 6.7, в bin файле = 6.7.
Температура в txt файле = 4.8, в bin файле = 4.8.
Температура в txt файле = 8.2, в bin файле = 8.2.
Температура в txt файле = 9.9, в bin файле = 9.9.
Температура в txt файле = 9.8, в bin файле = 9.8.
Температура в txt файле = 8.6, в bin файле = 8.6.
Температура в txt файле = 8.8, в bin файле = 8.8.
Температура в txt файле = 7.3, в bin ф

### Задание 4
Используя срезы извлеките нечетные элементы матрицы А. 

In [6]:
A[:, 1::2]


NameError: name 'A' is not defined

### Задание 5
Используйте массив из задания 1 (таблицу умножения) извлеките из него при помощи маски все числа кратные 3. 

In [ ]:
M = array([[j*i for j in range(1,11)] for i in range(2, 11)])

print(M)

mask = mod(M, 3) == 0

print(mask)

M[mask]

[[  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[ 0  0  6  0  0 12  0  0 18  0]
 [ 3  6  9 12 15 18 21 24 27 30]
 [ 0  0 12  0  0 24  0  0 36  0]
 [ 0  0 15  0  0 30  0  0 45  0]
 [ 6 12 18 24 30 36 42 48 54 60]
 [ 0  0 21  0  0 42  0  0 63  0]
 [ 0  0 24  0  0 48  0  0 72  0]
 [ 9 18 27 36 45 54 63 72 81 90]
 [ 0  0 30  0  0 60  0  0 90  0]]


array([ 6, 12, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 12, 24, 36, 15,
       30, 45,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 21, 42, 63, 24, 48,
       72,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 30, 60, 90])

### Задание 7
Разбить массив таблицы умножения из задания 1 на два массива содержащие четные и нечетные значения, а затем собрать его в исходное состояние используя choose()

In [ ]:
M = array([[j*i for j in range(1,11)] for i in range(2, 11)])

mask = mod(M, 2) == 0
mask2 = mod(M, 2) != 0

M1 = M.copy()
M2 = M.copy()

M1[mask] = 0
M2[mask2] = 0

print(M1, M2, sep="\n")

print(choose(mask, [M1, M2]))

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 3  0  9  0 15  0 21  0 27  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 5  0 15  0 25  0 35  0 45  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 7  0 21  0 35  0 49  0 63  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 9  0 27  0 45  0 63  0 81  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
[[  2   4   6   8  10  12  14  16  18  20]
 [  0   6   0  12   0  18   0  24   0  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  0  10   0  20   0  30   0  40   0  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  0  14   0  28   0  42   0  56   0  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  0  18   0  36   0  54   0  72   0  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27

### Задание 8
Даны вектора v1(0,1,2,3,4) v2(5,6,7,8,9) найти угол между ними, учитывая что косинус угла между векторами можно найти как отношения их скалярного произведения к их длинам.

In [8]:
import math
from math import pi

v1 = arange(0, 5, 1)
v2 = arange(5, 10, 1)
print(v1, v2)

# Скалярное произведение
pr = sum(v1*v2)

v1 = v1*v1

v2 = v2*v2

dv1 = sum(v1)**0.5

dv2 = sum(v2)**0.5

angl = math.acos(pr/(dv1*dv2)) 

# угол между векторами
print(angl * (180/pi))

[0 1 2 3 4] [5 6 7 8 9]
23.842636023792355


### Задача 9
Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержающую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы. Если для матрицы не у дается найти обратную, видимо этому мешает нулевое значение детерминанта.

In [ ]:
M1 = zeros((5,5))

M2 = zeros((5,5))

#print(M1, M2, sep='\n')

M1[::2, ::2] = 5
M1[1::2, 1::2] = 5

print("Матрица: 1\n", M1)


M2 = array([[0. if i <j else 5. for i in range(5)] for j in range(5)])

print("Матрица: 2\n", M2)


print("Детерминант матрицы 1: ", linalg.det(M1))
print("Детерминант матрицы 1: ", linalg.det(M2))

print("Обратная матрица", 1/linalg.det(M1)*M1.T)
print(1/linalg.det(M2)*M2.T)

Матрица: 1
 [[5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]]
Матрица: 2
 [[5. 5. 5. 5. 5.]
 [0. 5. 5. 5. 5.]
 [0. 0. 5. 5. 5.]
 [0. 0. 0. 5. 5.]
 [0. 0. 0. 0. 5.]]
0.0
3124.999999999999
[[inf nan inf nan inf]
 [nan inf nan inf nan]
 [inf nan inf nan inf]
 [nan inf nan inf nan]
 [inf nan inf nan inf]]
[[0.0016 0.     0.     0.     0.    ]
 [0.0016 0.0016 0.     0.     0.    ]
 [0.0016 0.0016 0.0016 0.     0.    ]
 [0.0016 0.0016 0.0016 0.0016 0.    ]
 [0.0016 0.0016 0.0016 0.0016 0.0016]]


C:\Users\AndroidS\AppData\Local\Temp\ipykernel_47000\3522139215.py:21: RuntimeWarning: divide by zero encountered in double_scalars
  print(1/linalg.det(M1)*M1.T)
C:\Users\AndroidS\AppData\Local\Temp\ipykernel_47000\3522139215.py:21: RuntimeWarning: invalid value encountered in multiply
  print(1/linalg.det(M1)*M1.T)
